### ISSUE TITLE
upload to codecov hanging in github actions

### ISSUE THREAD

**Issue by kkappler** [simpeg/aurora#325]
This [job](https://github.com/simpeg/aurora/actions/runs/8861647410/job/24333742735) is taking a long time to uplodad.

I noticed in my `.github/workflows/tests.yaml` that we are still using v1 .. maybe this is related?

```
- name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: false
```
I saw this message as well:

`Please upload with the Codecov repository upload token to resolve issue`

@jcapriot I tried following the instructions [here](https://docs.codecov.com/docs/adding-the-codecov-token), but it seems that maybe I don't have permission to access the token via simpeg codecov account -- is that possible?

**Comment by jcapriot** [comment]
Yeah, codecov no longer supports tokenless upload. I’ve just added the CODECOV_TOKEN as a secret variable for this repo. You should probably update to the new version of the uploader action (v4).

You’ll need to pass this token to the action as well:
```
- name: Upload coverage reports to Codecov
    uses: codecov/codecov-action@v4
    with:
      token: ${{ secrets.CODECOV_TOKEN }}
```
