### ISSUE TITLE
unexpected python version in gitactions tests 

### ISSUE THREAD

**Issue by kkappler** [simpeg/aurora#88]
When git actions runs, it is expected to run python 3.6, then 3.7, then 3.8, 

However it is running 3.9 in every case.  Probably an issue with .github/workflows/tests.yaml

https://docs.github.com/en/github-ae@latest/actions/guides/building-and-testing-python

![Screenshot from 2021-09-03 15-44-04](https://user-images.githubusercontent.com/1154939/132071873-ee627d72-5e7b-4467-8a37-5ca5148a19bc.png)

```
jobs:
  setup-build:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        conda-channels: conda-forge
        python-version: ${{ matrix.python-version }}

    - name: Install Env
      shell: bash
      run: |
        python --version
        conda create -n aurora-test
        source activate aurora-test
        conda config --add channels conda-forge
        conda install pytest
...
```
